/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yoursunfurniture;

import ManajemenFurniture.Furniture;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Pelanggan
     */
    public MenuAdmin() {
        initComponents();
        readProduk();
    }
    
    public void readProduk(){
        Furniture furn = new Furniture(null, null, null, 0,0);
        
        jTable1.setModel(furn.read());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel1.setText("ID Produk");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 90, 70, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 250, 150, 22);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel2.setText("Nama Produk");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 70, 14);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setText("Kategori");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setText("Harga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 204, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setText("Stok");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 40, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/person_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 50, 30, 31);

        jButton4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton4.setText("Tambah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 130, 72, 21);

        jButton5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(280, 180, 72, 21);

        jButton6.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton6.setText("Hapus");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(280, 230, 72, 21);

        jTable1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Produk", "Kategori", "Harga", "Stok"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 290, 360, 150);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 90, 150, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 130, 150, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(110, 170, 150, 22);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(110, 210, 150, 22);

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(269, 51, 80, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/Background.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 360, 440);

        setBounds(0, 0, 374, 447);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Akun akn = new Akun();
        this.dispose();
        akn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login lgn = new Login();
        this.dispose();
        lgn.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id = jTextField3.getText();
        String nama = jTextField4.getText();
        String kategori = jTextField5.getText();
        

    if (id.isEmpty() || nama.isEmpty() || kategori.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Silahkan isi data produk terlebih dahulu", "Peringatan", JOptionPane.WARNING_MESSAGE);
    } else {
        int stok = 0;
        int harga = 0;

        try {
            stok = Integer.parseInt(jTextField2.getText());
            harga = Integer.parseInt(jTextField6.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Stok dan harga harus diisi dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Furniture frn = new Furniture(id, nama, kategori, harga, stok);
        boolean createSuccess = frn.createProduk();

        if (createSuccess) {
            JOptionPane.showMessageDialog(null, "Data Produk berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            readProduk();
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField3.setEnabled(true);
        }
    }
    
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField3.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String id = jTextField3.getText();
        String nama = jTextField4.getText();
        String kategori = jTextField5.getText();

        if (id.isEmpty() || nama.isEmpty() || kategori.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih produk yang ingin diupdate", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            int stok = 0;
            int harga = 0;

            try {
                stok = Integer.parseInt(jTextField2.getText());
                harga = Integer.parseInt(jTextField6.getText());

                if (stok < 0 || harga < 0) {
                    JOptionPane.showMessageDialog(null, "Stok dan harga harus diisi dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Stok dan harga harus diisi dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Furniture frn = new Furniture(id, nama, kategori, harga, stok);
            boolean updateSuccess = frn.updateProduk();

            if (updateSuccess) {
                JOptionPane.showMessageDialog(null, "Data Produk berhasil diubah!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                readProduk();
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField3.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        
        String id = tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String nama = tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String kategori = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
        int stok = Integer.parseInt(tblModel.getValueAt(jTable1.getSelectedRow(), 4).toString());
        int harga = Integer.parseInt(tblModel.getValueAt(jTable1.getSelectedRow(), 3).toString());
        
        jTextField2.setText(String.valueOf(stok));
        jTextField3.setText(id);
        jTextField4.setText(nama);
        jTextField5.setText(kategori);
        jTextField6.setText(String.valueOf(harga));

        jTextField3.setEnabled(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String id = jTextField3.getText();
        String nama = jTextField4.getText();
        String kategori = jTextField5.getText();

        if (id.isEmpty() || nama.isEmpty() || kategori.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih produk yang ingin dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            int stok = 0;
            int harga = 0;

            try {
                stok = Integer.parseInt(jTextField2.getText());
                harga = Integer.parseInt(jTextField6.getText());

                if (stok < 0 || harga < 0) {
                    JOptionPane.showMessageDialog(null, "Stok dan harga harus diisi dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Stok dan harga harus diisi dengan benar", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Furniture frn = new Furniture(id, nama, kategori, harga, stok);
            boolean updateSuccess = frn.deleteProduk();

            if (updateSuccess) {
                JOptionPane.showMessageDialog(null, "Data Produk berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                readProduk();
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField3.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
